apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::337689099048:user/developeriq
      username: developeriq
      groups:
        - system:masters